name: budgets
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.4
  currency_text_input_formatter: ^2.1.5
  dartz: ^0.10.1
  drift: ^1.4.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cupertino_localizations: ^1.0.1
  flutter_facebook_auth: ^4.1.1
  flutter_hooks: ^0.18.2+1
  flutter_iconpicker: ^3.1.2
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.1.0+2
  flutter_slidable: ^1.2.0
  flutter_sticky_header: ^0.6.1
  freezed_annotation: ^1.1.0
  google_fonts: ^2.1.1
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+10
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  page_indicator: ^0.4.1
  path: 1.8.0
  path_provider: ^2.0.9
  sqlite3_flutter_libs: ^0.5.4
  tuple: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.7
  drift_dev: ^1.4.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  lint: ^1.8.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700      
